services:
  - type: web
    name: bot-voice
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
